### ISSUE TITLE
question: stricter country code mask

### ISSUE THREAD

**Issue by dalawwa** [dimitrinicolas/text-mask-vat-id#8]
This is really helpful work, thank you.

I wonder whether we could enforce a stricter mask while accepting all currently supported formats by changing the following

https://github.com/dimitrinicolas/text-mask-vat-id/blob/b80a8a7d0ae6a9b89f69edb31711b51c0a29d411/src/index.js#L14

to `const COUNTRY_CODE_MASK = [/[A-Za-z]/, /[A-Za-z]/]`.

Then recommend to add a pipe to uppercase the country code in the README.

**Comment by dimitrinicolas** [comment]
Thank you!

Sure, `[A-Za-z]` is way better! We could even think about having a list of valid country codes, but a-Z is great haha!

You can open a Pull Request, otherwise I will find the time to make this change.
